[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anderdzi = "HqAguZH2aj1sSc4Zi6Ck1MBV1bpz1z4cyZUnYT3bTztN"

[programs.localnet]
anderdzi = "6xgUzv1pYovTNK1QYAEK5xRdHeTwaum6rGX6AEJqhA1x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --test --import tsx tests/treasury.ts tests/vault.ts tests/funds.ts tests/lifecycle.ts tests/beneficiaries.ts tests/staking.ts tests/watcher.ts"
